plugins {
    id 'groovy'
    id 'application'
}

group = 'boghus.codereview'
version = '0.1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation localGroovy()
}

application {
    mainClass = 'boghus.codereview.action.Main'
}

tasks.withType(GroovyCompile).configureEach {
    options.encoding = 'UTF-8'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
