package com.boghus.codereview.output

import groovy.transform.CompileStatic

/**
 * Writes the markdown that will become the PR comment body.
 *
 * <h3>Identity</h3>
 *
 * The agent publishes under the visible name {@code Code Review Agent by boghus}.
 * Bodies begin with {@link #COMMENT_MARKER}, which is the lookup key the
 * action uses to find the previous run's comment and replace it in place.
 *
 * <h3>Idempotency</h3>
 *
 * The marker is the contract between the writer and the composite action
 * steps that post the comment. Idempotency is guaranteed by the combination
 * of (a) every body carrying the marker and (b) the composite action steps
 * wiring it through {@code body-regex} on the find-comment step. If those
 * steps are ever replaced, the replacement must honour the marker contract
 * or every push will spawn a new comment.
 *
 * <h3>AI disclaimer</h3>
 *
 * Bodies that originate from an AI response (see
 * {@link #writeAiGenerated(String, String)}) carry the "AI-generated review"
 * disclaimer. Bodies written via {@link #write(String, String)} do NOT, since
 * they cover failure / misconfiguration / too-large / empty-diff paths where
 * no model was invoked and calling them "AI-generated" would be misleading.
 *
 * <h3>Compatibility with v1</h3>
 *
 * v1 used {@code <!-- code-review-agent -->}. {@link #LEGACY_MARKER} is
 * recognised by the action steps only as a search key, so existing comments
 * from v1 are picked up and replaced in place. New comments are always
 * tagged with {@link #COMMENT_MARKER}.
 */
@CompileStatic
class ReviewReportWriter {

    /** Marker written on every body. Used by the action to find and update the comment. */
    static final String COMMENT_MARKER = '<!-- code-review-agent-by-boghus -->'

    /** Legacy v1 marker. Accepted as a search key during the v1→v2 migration window. */
    static final String LEGACY_MARKER = '<!-- code-review-agent -->'

    /** Disclaimer prefix added to bodies whose content originated from the AI provider. */
    static final String AI_DISCLAIMER = '> ⚠️ **AI-generated review:** This review was generated by an AI model and may contain **false positives, false negatives, or incorrect recommendations**. Please validate the findings before making changes.\n'

    private final String actionRef
    private final String actionSha

    ReviewReportWriter() {
        this(System.getenv('CRA_ACTION_REF'), System.getenv('CRA_ACTION_SHA'))
    }

    ReviewReportWriter(String actionRef, String actionSha) {
        this.actionRef = actionRef?.trim()
        this.actionSha = actionSha?.trim()
    }

    /**
     * Writes a comment body that did NOT come from the AI provider (e.g.
     * empty diff, failure, misconfiguration, diff too large). The version
     * footer is still added when metadata is available, but no AI disclaimer
     * is included.
     */
    void write(String outputPath, String body) {
        writeInternal(outputPath, body, false)
    }

    /**
     * Writes a comment body that DID come from the AI provider. Adds the AI
     * disclaimer in addition to the version footer.
     */
    void writeAiGenerated(String outputPath, String body) {
        writeInternal(outputPath, body, true)
    }

    private void writeInternal(String outputPath, String body, boolean fromAi) {
        String normalizedBody = body == null ? '' : body
        String safeBody = normalizedBody.endsWith('\n') ? normalizedBody : normalizedBody + '\n'
        String disclaimer = fromAi ? AI_DISCLAIMER : ''
        String footer = renderVersionFooter()
        new File(outputPath).write("${COMMENT_MARKER}\n${safeBody}${disclaimer}${footer}", 'UTF-8')
    }

    private String renderVersionFooter() {
        if (!actionRef) {
            return ''
        }
        String label = describeRef(actionRef)
        String versionLine = "Version: ${actionRef}${label ? " (${label})" : ''}\n"
        String commitLine = actionSha ? "Commit: ${actionSha}\n" : ''
        return "\n---\n🤖 Code Review Agent\n${versionLine}${commitLine}"
    }

    /**
     * Classifies an action reference for the footer. Recognises:
     * <ul>
     *   <li>{@code refs/tags/<name>} → {@code "tag"}</li>
     *   <li>{@code refs/heads/<name>} → {@code "branch"}</li>
     *   <li>a 40-char hex SHA → {@code "sha"}</li>
     *   <li>otherwise → {@code ""} (no label)</li>
     * </ul>
     */
    private static String describeRef(String ref) {
        if (ref.startsWith('refs/tags/')) {
            return 'tag'
        }
        if (ref.startsWith('refs/heads/')) {
            return 'branch'
        }
        if (ref ==~ /[0-9a-f]{40}/) {
            return 'sha'
        }
        return ''
    }

    void writeEmpty(String outputPath) {
        write(outputPath, """## 🤖 Code Review Agent by boghus

No changes to review.
""")
    }

    void writeFailure(String outputPath, String message) {
        write(outputPath, """## ⚠️ Code Review Agent by boghus unavailable

${message}

The automated review is non-blocking. Re-run the workflow when the AI provider is available again.
""")
    }

    void writeMisconfigured(String outputPath, String message) {
        write(outputPath, """## ⚠️ Code Review Agent by boghus skipped

${message}

The automated review was skipped because the required configuration or trusted review rules could not be loaded or validated. This is non-blocking; fix the configuration or rules and re-run the workflow.
""")
    }

    void writeTrustedRulesFailure(String outputPath, String reason) {
        write(outputPath, """## ⚠️ Code Review Agent by boghus skipped

${reason}

The automated review was skipped because trusted review rules are required to build the review prompt. This is **non-blocking**; fix the rules or configuration and re-run the workflow.
""")
    }

    void writeTooLarge(String outputPath, String reason, int bytes, int lines, int maxBytes, int maxLines) {
        write(outputPath, """## ⚠️ Code Review Agent by boghus skipped (diff too large)

${reason}

- Diff size: **${bytes} bytes**, **${lines} lines**
- Configured limits: **${maxBytes} bytes**, **${maxLines} lines**

The automated review was skipped to avoid sending an oversized context to the AI provider, which typically results in 4xx errors or quota exhaustion. To re-enable, raise the limits via the action inputs (`max-diff-bytes`, `max-diff-lines`) or split the Pull Request into smaller changes.
""")
    }
}
